from openpi.configs.base import *
import openpi.training.utils as _utils
from openpi.training.frame_attributes_preprocessors import HfColumnIsValidPreprocessor

DEBUG_MODE = False

TASK_NAME = "pi05_pickplace_14_dim_subtask_discrete_action_cond_160token_lossweighted"
EXP_NAME = TASK_NAME + "_exp"
ASSET_ID = "20260312"

# Dataset settings
ROOT_DIR = "/mnt/workspace/shared/datasets/anyverse_pickAndplace_record_tmp"
ACTION_SEQUENCE_KEYS = ("action",)
UNIFY_ACTION_SPACE = False
DELTA_ACTION_MASK_INDICES = [6, -1, 6, -1]

ALIGN_DIM = sum(np.abs(DELTA_ACTION_MASK_INDICES).tolist())
TARGET_ACTION_DIM = range(14)
REPO_ID = [
    # Total episodes: 5750, total time: 46.97 hours
    "record.pick.place.bipiper.v0107.1",
    "record.pick.place.bipiper.v0107.2",
    "record.pick.place.bipiper.v0107.3",
    "record.pick.place.bipiper.v0107.4",
    "record.pick.place.bipiper.v0107.6",
    "record.pick.place.bipiper.v0107.7",
    "record.pick.place.bipiper.v0108.1",
    "record.pick.place.bipiper.v0108.10",
    "record.pick.place.bipiper.v0108.11",
    "record.pick.place.bipiper.v0108.12",
    "record.pick.place.bipiper.v0108.13",
    "record.pick.place.bipiper.v0108.14",
    "record.pick.place.bipiper.v0108.15",
    "record.pick.place.bipiper.v0108.16",
    "record.pick.place.bipiper.v0108.17",
    "record.pick.place.bipiper.v0108.18",
    "record.pick.place.bipiper.v0108.19",
    "record.pick.place.bipiper.v0108.2",
    "record.pick.place.bipiper.v0108.20",
    "record.pick.place.bipiper.v0108.21",
    "record.pick.place.bipiper.v0108.22",
    "record.pick.place.bipiper.v0108.3",
    "record.pick.place.bipiper.v0108.4",
    "record.pick.place.bipiper.v0108.6",
    "record.pick.place.bipiper.v0108.7",
    "record.pick.place.bipiper.v0108.9",
    "record.pick.place.bipiper.v0109.01",
    "record.pick.place.scheme2.bipiper.v0109.01",
    "record.pick.place.scheme2.bipiper.v0109.02",
    "record.pick.place.scheme2.bipiper.v0109.03",
    "record.pick.place.scheme2.bipiper.v0109.04",
    "record.pick.place.scheme2.bipiper.v0109.05",
    "record.pick.place.scheme2.bipiper.v0109.06",
    "record.pick.place.scheme2.bipiper.v0109.07",
    "record.pick.place.scheme2.bipiper.v0109.08",
    "record.pick.place.scheme2.bipiper.v0109.09",
    "record.pick.place.scheme2.bipiper.v0109.10",
    "record.pick.place.scheme2.bipiper.v0109.11",
    "record.pick.place.scheme2.bipiper.v0109.12",
    "record.pick.place.scheme2.bipiper.v0109.13",
    "record.pick.place.scheme2.bipiper.v0112.1",
    "record.pick.place.scheme2.bipiper.v0112.2",
    "record.pick.place.scheme2.bipiper.v0112.3",
    "record.pick.place.scheme2.bipiper.v0112.4",
    "record.pick.place.scheme2.bipiper.v0112.5",
    "record.pick.place.scheme2.otherbackgrounds.bipiper.v0112.10",
    "record.pick.place.scheme2.otherbackgrounds.bipiper.v0112.11",
    "record.pick.place.scheme2.otherbackgrounds.bipiper.v0112.6",
    "record.pick.place.scheme2.otherbackgrounds.bipiper.v0112.7",
    "record.pick.place.scheme2.otherbackgrounds.bipiper.v0112.8",
    "record.pick.place.scheme2.otherbackgrounds.bipiper.v0112.9",
    "record.pick.place.scheme2.otherbackgrounds.withmiss.bipiper.v0112.12",
    "record.pick.place.move.bipiper.v0113.1",
    "record.pick.place.move.bipiper.v0113.2",
    "record.pick.place.move.bipiper.v0113.4",
    "record.pick.place.move.bipiper.v0113.5",
    "record.pick.place.move.bipiper.v0113.6",
    "record.pick.place.move.bipiper.v0113.7",
    "record.pick.place.move.bipiper.v0113.8",
    "record.pick.place.move.targetintray.bipiper.v0114.1",
    "record.pick.place.move.targetintray.bipiper.v0114.2",
    "record.pick.place.move.targetintray.bipiper.v0114.3",
    "record.pick.place.move.withmiss.bipiper.v0114.5",
    "record.pick.place.move.multiheight.bipiper.v0115.4",
    "record.pick.place.move.targetintray.bipiper.v0115.2",
    "record.pick.place.move.targetintray.bipiper.v0115.3",
    "record.pick.place.multiobj.bipiper.v0116.5",
    "record.pick.place.multiobj.bipiper.v0116.6",
    "record.pick.place.scheme3.multiheight_bipiper.v0116.4",
    "record.pick.place.multiobj.bipiper.v0119.7",
    "record.pick.place.scheme3.multiheight_bipiper.v0119.1",
    "record.pick.place.scheme3.multiheight_bipiper.v0119.2",
    "record.pick.place.scheme3.multiheight_bipiper.v0119.3",
    "record.pick.place.scheme3.multiheight_bipiper.v0119.4",
    "record.pick.place.scheme3.multiheight_bipiper.v0119.5",
    "record.pick.place.scheme3.multiheight_bipiper.v0119.6",
    "record.pick.place.scheme3.bipiper.v0120.3",
    "record.pick.place.multiobj.bipiper.v0121.7",
    "record.pick.place.scheme3.bipiper.v0121.1",
    "record.pick.place.scheme3.bipiper.v0121.2",
    "record.pick.place.scheme3.bipiper.v0121.3",
    "record.pick.place.scheme3.bipiper.v0121.4",
    "record.pick.place.scheme3.bipiper.v0121.5",
    "record.pick.place.scheme3.bipiper.v0121.6",
    "record.pick.place.scheme2.newobj.bipiper.v0122.2",
    "record.pick.place.scheme2.newobj.bipiper.v0122.3",
    "record.pick.place.scheme2.newobj.bipiper.v0122.4",
    "record.pick.place.scheme2.newobj.bipiper.v0122.5",
    "record.pick.place.multiob.bipiper.v0123.6",
    "record.pick.place.scheme2.newobj.bipiper.v0123.1",
    "record.pick.place.scheme2.newobj.bipiper.v0123.2",
    "record.pick.place.scheme2.newobj.bipiper.v0123.3",
    "record.pick.place.scheme2.newobj.bipiper.v0123.4",
    "record.pick.place.scheme2.newobj.bipiper.v0123.5",
    "record.pick.place.move.newobj.bipiper.v0126.2",
    "record.pick.place.move.newobj.bipiper.v0126.3",
    "record.pick.place.restore_container.newobj.bipiper.v0126.6",
    "record.pick.place.onlyrestore_container.bipiper.v0127.1",
    "record.pick.place.onlyrestore_container.bipiper.v0127.2",
    "record.pick.place.onlyrestore_container.bipiper.v0127.3",
    "record.pick.place.withrestore_container.bipiper.v0127.4",
    "record.pick.place.movetarget.bipiper.v0128.6",
    "record.pick.place.movetarget.bipiper.v0128.7",
    "record.pick.place.onlyrestore_container.bipiper.v0128.1",
    "record.pick.place.onlyrestore_container.bipiper.v0128.2",
    "record.pick.place.onlyrestore_container.bipiper.v0128.3",
    "record.pick.place.onlyrestore_container.bipiper.v0128.4",
    "record.pick.place.onlyrestore_container.bipiper.v0128.5",
    "record.pick.place.movetarget.bipiper.v0129.1",
    "record.pick.place.onlyrestore_container.bipiper.v0129.4",
    "record.pick.place.onlyrestore_container.bipiper.v0129.5",
    "record.pick.place.withrestore_container.bipiper.v0130.1",
    "record.pick.place.withrestore_container.bipiper.v0130.2",
    "record.pick.place.withrestore_container.bipiper.v0130.3",
    "record.pick.place.withrestore_container.bipiper.v0130.4",
    "record.pick.place.withrestore_container.bipiper.v0130.5",
    "record.pick.place.onlyrestore_container.multitime.bipiper.v0202.1",
    "record.pick.place.onlyrestore_container.multitime.bipiper.v0202.2",
    "record.pick.place.onlyrestore_container.multitime.bipiper.v0202.3",
    "record.pick.place.withrestore_container.bipiper.v0202.4",
    "record.pick.place.withrestore_container.bipiper.v0202.5",
    "record.pick.place.movetarget.bipiper.v0203.4",
    "record.pick.place.movetarget.bipiper.v0203.5",
    "record.pick.place.onlyrestore_container.multitime.bipiper.v0203.6",
    "record.pick.place.withrestore_container.bipiper.v0203.1",
    "record.pick.place.withrestore_container.bipiper.v0203.2",
    "record.pick.place.withrestore_container.bipiper.v0203.3",
    "record.pick.place.onlyrestore_container.multitime.bipiper.v0204.1",
    "record.pick.place.onlyrestore_container.multitime.bipiper.v0204.2",
    "record.pick.place.withrestore_container.multitime.bipiper.v0204.3",
    "record.pick.place.withrestore_container.multitime.bipiper.v0204.4",
    "record.pick.place.withrestore_container.multitime.bipiper.v0204.5",
    "record.pick.place.withrestore_container.multitime.bipiper.v0205.1",
    "record.pick.place.withrestore_container.multitime.bipiper.v0205.2",
    "record.pick.place.withrestore_container.multitime.bipiper.v0205.3",
    "record.pick.place.withrestoremulti_container.multitime.bipiper.v0206.1",
    "record.pick.place.withrestoremulti_container.multitime.bipiper.v0206.2",
    "record.pick.place.withrestore_container.multitime.bipiper.v0209.1",
    "record.pick.place.withrestore_container.multitime.bipiper.v0209.2",
    "record.pick.place.withrestoremulti_container.multitime.bipiper.v0209.3",
    "record.pick.place.withrestoremulti_container.multitime.bipiper.v0209.4",
    "record.pick.place.withrestoremulti_container.multitime.bipiper.v0209.5",
    "record.pick.place.pickfromcontainer.bipiper.v0210.10",
    "record.pick.place.pickfromcontainer.bipiper.v0210.11",
    "record.pick.place.pickfromcontainer.bipiper.v0210.9",
    "record.pick.place.pickfromcontainer.bipiper.v0211.1",
    "record.pick.place.pickfromcontainer.bipiper.v0211.2",
    "record.pick.place.pickfromcontainer.bipiper.v0211.3",
    "record.pick.place.pushotherout.bipiper.v0211.4",
    "record.pick.place.pushotherout.bipiper.v0212.1",
    "record.pick.place.pushotherout.bipiper.v0212.2",
    "record.pick.place.pushotherout.bipiper.v0212.3",
    "record.pick.place.pushotherout.bipiper.v0212.4",
    "record.pick.place.pushotherout.bipiper.v0212.5",
    "record.pick.place.pushotherout.bipiper.v0212.6",
    "record.pick.place.pushotherout.bipiper.v0212.7",
    "record.pick.place.pushotherout.bipiper.v0212.8",
    "record.pick.place.pickfromcontainer.bipiper.v0213.10",
    "record.pick.place.pickfromcontainer.bipiper.v0213.4",
    "record.pick.place.pickfromcontainer.bipiper.v0213.5",
    "record.pick.place.pickfromcontainer.bipiper.v0213.6",
    "record.pick.place.pickfromcontainer.bipiper.v0213.7",
    "record.pick.place.pickfromcontainer.bipiper.v0213.8",
    "record.pick.place.pickfromcontainer.bipiper.v0213.9",
    "record.pick.place.pushotherout.bipiper.v0213.1",
    "record.pick.place.pushotherout.bipiper.v0213.2",
    "record.pick.place.pushotherout.bipiper.v0213.3",
    "record.pick.place.pushotherout.bipiper.v0214.1",
    "record.pick.place.pushotherout.bipiper.v0214.2",
    "record.pick.place.pushotherout.bipiper.v0214.3",
    "record.pick.place.pushotherout.bipiper.v0214.4",
    "record.pick.place.pushotherout.bipiper.v0214.5",
    "record.pick.place.pushotherout.bipiper.v0214.6",
    "record.pick.place.pushotherout.bipiper.v0214.7",
    "record.pick.place.pushotherout.bipiper.v0224.1",
    "record.pick.place.pushotherout.bipiper.v0224.2",
    "record.pick.place.pushotherout.bipiper.v0224.3",
    "record.pick.place.pushotherout.bipiper.v0224.4",
    "record.pick.place.pushotherout.bipiper.v0224.5",
    "record.pick.place.pushotherout.bipiper.v0225.1",
    "record.pick.place.pushotherout.bipiper.v0225.2",
    "record.pick.place.pushotherout.bipiper.v0225.4",
    "record.pick.place.pushotherout.bipiper.v0225.5",
    # begin with push other out subtask anno
    "record.pick.place.pushotherout.bipiper.v0225.6",
    "record.pick.place.pushotherout.bipiper.v0225.7",
    "record.pick.place.pushotherout.bipiper.v0225.8",
    "record.pick.place.pushotherout.bipiper.v0225.9",
    # 0226
    "record.pick.place.pushotherout.bipiper.v0226.3",
    # 0227 Total episodes: 255, total time: 2.04 hours
    "record.pick.place.pushotherout.bipiper.v0227.1",
    "record.pick.place.pushotherout.bipiper.v0227.2",
    "record.pick.place.pushotherout.bipiper.v0227.3",
    "record.pick.place.pushotherout.bipiper.v0227.4",
    "record.pick.place.pushotherout.bipiper.v0227.5",
    "record.pick.place.pushotherout.bipiper.v0227.6",
    "record.pick.place.pushotherout.bipiper.v0227.7",
    "record.pick.place.onelyunzip_container.bipiper.v0227.8",
]
# TrainConfig
BATCH_SIZE = 128
NUM_WORKERS = 8
TRAIN_STEPS = 60000
PRETRAINED_WEIGHT_PATH = "openpi-assets/checkpoints/pi05_base/params"

if DEBUG_MODE:
    BATCH_SIZE = 2
    NUM_WORKERS = 1
    REPO_ID = REPO_ID[:1]

FRAME_ATTRS_PREPROCESSORS = [
    HfColumnIsValidPreprocessor(column_name="is_valid"),
]

cfg = TrainConfig(
    name=TASK_NAME,
    exp_name=EXP_NAME,
    model=pi0_config.Pi0Config(
        pi05_subtask_fast=True,
        pi05_with_subtask=True,
        pi05_with_fast_action=True,
        subtask_as_action_cond=True,
        action_loss_weight=6.0,
        subtask_loss_weight=0.5,
        fast_action_loss_weight=0.02,
        max_token_len=160,
        action_horizon=32,
    ),
    data=Gr00tLerobotDataConfig(
        assets=AssetsConfig(asset_id=ASSET_ID),
        root_dir=ROOT_DIR,
        repo_id=REPO_ID,
        base_config=DataConfig(
            prompt_from_episode=True,
            parquet_dir="data_refractor",
            action_sequence_keys=ACTION_SEQUENCE_KEYS,
            subtask_info={
                "subtask_anno_path": "annotations/episode_subtask_annotations.jsonl",
            },
            frame_attributes_preprocessors=FRAME_ATTRS_PREPROCESSORS,
        ),
        extra_delta_transform=False,
        use_delta_joint_actions=True,
        delta_action_mask_indices=DELTA_ACTION_MASK_INDICES,
        public_dataset_camera_map=_utils.PUBLIC_DATASET_MAP,
        align_dim=ALIGN_DIM,
        target_action_dim=TARGET_ACTION_DIM,
        unify_action_space=UNIFY_ACTION_SPACE,
    ),
    weight_loader=weight_loaders.CheckpointWeightLoader(PRETRAINED_WEIGHT_PATH),
    num_train_steps=TRAIN_STEPS,
    batch_size=BATCH_SIZE,
    num_workers=NUM_WORKERS,
    log_interval=200,
    # How often (in steps) to save checkpoints.
    save_interval=TRAIN_STEPS // 2,
    # If set, any existing checkpoints matching step % keep_period == 0 will not be deleted.
    keep_period=TRAIN_STEPS // 2,
    overwrite=False,
    resume=True,
)
