# Copyright 2024 The HuggingFace Inc. team. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Records a dataset. Actions for the robot can be either generated by teleoperation or by a policy.

Example:

```shell
lerobot-record \
    --robot.type=so100_follower \
    --robot.port=/dev/tty.usbmodem58760431541 \
    --robot.cameras="{laptop: {type: opencv, camera_index: 0, width: 640, height: 480}}" \
    --robot.id=black \
    --dataset.repo_id=aliberts/record-test \
    --dataset.num_episodes=2 \
    --dataset.single_task="Grab the cube" \
    # <- Teleop optional if you want to teleoperate to record or in between episodes with a policy \
    # --teleop.type=so100_leader \
    # --teleop.port=/dev/tty.usbmodem58760431551 \
    # --teleop.id=blue \
    # <- Policy optional if you want to record with a policy \
    # --policy.path=${HF_USER}/my_policy \
```

Example recording with bimanual so100:
```shell
lerobot-record \
  --robot.type=bi_so100_follower \
  --robot.left_arm_port=/dev/tty.usbmodem5A460851411 \
  --robot.right_arm_port=/dev/tty.usbmodem5A460812391 \
  --robot.id=bimanual_follower \
  --robot.cameras='{
    left: {"type": "opencv", "index_or_path": 0, "width": 640, "height": 480, "fps": 30},
    top: {"type": "opencv", "index_or_path": 1, "width": 640, "height": 480, "fps": 30},
    right: {"type": "opencv", "index_or_path": 2, "width": 640, "height": 480, "fps": 30}
  }' \
  --teleop.type=bi_so100_leader \
  --teleop.left_arm_port=/dev/tty.usbmodem5A460828611 \
  --teleop.right_arm_port=/dev/tty.usbmodem5A460826981 \
  --teleop.id=bimanual_leader \
  --display_data=true \
  --dataset.repo_id=${HF_USER}/bimanual-so100-handover-cube \
  --dataset.num_episodes=25 \
  --dataset.single_task="Grab and handover the red cube to the other arm"
```
"""

import logging
import time
import pygame
import requests
import io
import threading
import os
import shutil
from dataclasses import asdict, dataclass
from pathlib import Path
from pprint import pformat

from lerobot.cameras import (  # noqa: F401
    CameraConfig,  # noqa: F401
)
from lerobot.cameras.opencv.configuration_opencv import OpenCVCameraConfig  # noqa: F401
from lerobot.cameras.realsense.configuration_realsense import RealSenseCameraConfig  # noqa: F401
from lerobot.configs import parser
from lerobot.configs.policies import PreTrainedConfig
from lerobot.datasets.image_writer import safe_stop_image_writer
from lerobot.datasets.lerobot_dataset import LeRobotDataset
from lerobot.datasets.utils import build_dataset_frame, hw_to_dataset_features
from lerobot.datasets.video_utils import VideoEncodingManager
from lerobot.policies.factory import make_policy
from lerobot.policies.pretrained import PreTrainedPolicy
from lerobot.robots import (  # noqa: F401
    Robot,
    RobotConfig,
    bi_so100_follower,
    arx_x5_python,
    hope_jr,
    koch_follower,
    make_robot_from_config,
    so100_follower,
    so101_follower,
    piper,
)
from lerobot.teleoperators import (  # noqa: F401
    Teleoperator,
    TeleoperatorConfig,
    bi_so100_leader,
    homunculus,
    koch_leader,
    make_teleoperator_from_config,
    so100_leader,
    so101_leader,
)
from lerobot.teleoperators.keyboard.teleop_keyboard import KeyboardTeleop
from lerobot.utils.control_utils import (
    init_keyboard_listener,
    is_headless,
    predict_action,
    sanity_check_dataset_name,
    sanity_check_dataset_robot_compatibility,
)
from lerobot.utils.robot_utils import busy_wait
from lerobot.utils.utils import (
    get_safe_torch_device,
    init_logging,
    log_say,
)
from lerobot.utils.visualization_utils import _init_rerun, log_rerun_data
from lerobot.utils.tts_config_parser import parse_record_config

# 设置音频驱动
os.environ["SDL_AUDIODRIVER"] = "pulse"


def play_sound_seq(
    text: str = "你好啊，我是三零九零。", reference_id: str = "taozi", tts_url: str = "http://127.0.0.1:8080/v1/tts"
):
    """播放TTS音频序列"""
    payload = {"text": text, "format": "wav", "reference_id": reference_id}
    wav_bytes = requests.post(tts_url, json=payload).content

    pygame.mixer.init()
    sound = pygame.mixer.Sound(io.BytesIO(wav_bytes))

    sound.set_volume(4200.0)  # 调整音量，1.0 为原始，2.0 放大一倍
    sound.play()

    time.sleep(sound.get_length() + 0.5)  # 多给 0.5s 缓冲
    pygame.mixer.quit()


def play_sound(
    text: str = "你好啊，我是三零九零。", reference_id: str = "taozi", tts_url: str = "http://127.0.0.1:8080/v1/tts"
):
    """在单独线程中播放TTS音频"""
    thread = threading.Thread(target=play_sound_seq, args=(text, reference_id, tts_url))
    thread.start()

@dataclass
class DatasetRecordConfig:
    # Dataset identifier. By convention it should match '{hf_username}/{dataset_name}' (e.g. `lerobot/test`).
    repo_id: str
    # A short but accurate description of the task performed during the recording (e.g. "Pick the Lego block and drop it in the box on the right.")
    single_task: str
    # Root directory where the dataset will be stored (e.g. 'dataset/path').
    root: str | Path | None = None
    # Limit the frames per second.
    fps: int = 30
    # Number of seconds for data recording for each episode.
    episode_time_s: int | float = 60
    # Number of seconds for resetting the environment after each episode.
    reset_time_s: int | float = 60
    # Number of episodes to record.
    num_episodes: int = 50
    # Encode frames in the dataset into video
    video: bool = True
    # Upload dataset to Hugging Face hub.
    push_to_hub: bool = True
    # Upload on private repository on the Hugging Face hub.
    private: bool = False
    # Add tags to your dataset on the hub.
    tags: list[str] | None = None
    # Number of subprocesses handling the saving of frames as PNG. Set to 0 to use threads only;
    # set to ≥1 to use subprocesses, each using threads to write images. The best number of processes
    # and threads depends on your system. We recommend 4 threads per camera with 0 processes.
    # If fps is unstable, adjust the thread count. If still unstable, try using 1 or more subprocesses.
    num_image_writer_processes: int = 0
    # Number of threads writing the frames as png images on disk, per camera.
    # Too many threads might cause unstable teleoperation fps due to main thread being blocked.
    # Not enough threads might cause low camera fps.
    num_image_writer_threads_per_camera: int = 4
    # Number of episodes to record before batch encoding videos
    # Set to 1 for immediate encoding (default behavior), or higher for batched encoding
    video_encoding_batch_size: int = 1

    def __post_init__(self):
        if self.single_task is None:
            raise ValueError("You need to provide a task as argument in `single_task`.")


@dataclass
class RecordConfig:
    robot: RobotConfig
    dataset: DatasetRecordConfig
    # Whether to control the robot with a teleoperator
    teleop: TeleoperatorConfig | None = None
    # Whether to control the robot with a policy
    policy: PreTrainedConfig | None = None
    # Display all cameras on screen
    display_data: bool = False
    # Use vocal synthesis to read events.
    play_sounds: bool = True
    # Resume recording on an existing dataset.
    resume: bool = False
    # record config
    tts_url: str = "http://127.0.0.1:8080/v1/tts"
    record_yaml_path: str | None = None  # 记录配置的yaml文件路径
    record_task: str | None = None  # 要录制的任务

    def __post_init__(self):
        # HACK: We parse again the cli args here to get the pretrained path if there was one.
        policy_path = parser.get_path_arg("policy")
        if policy_path:
            cli_overrides = parser.get_cli_overrides("policy")
            self.policy = PreTrainedConfig.from_pretrained(policy_path, cli_overrides=cli_overrides)
            self.policy.pretrained_path = policy_path

        if self.teleop is None and self.policy is None:
            if "arx" not in self.robot.type:
                raise ValueError("For robots with a mobile base, you need to provide a teleoperator or a policy to control the base.")
            else:
                logging.warning("No teleoperator or policy provided, the robot will stay still during recording.")
    @classmethod
    def __get_path_fields__(cls) -> list[str]:
        """This enables the parser to load config from the policy using `--policy.path=local/dir`"""
        return ["policy"]


@safe_stop_image_writer
def record_loop(
    robot: Robot,
    events: dict,
    fps: int,
    dataset: LeRobotDataset | None = None,
    teleop: Teleoperator | list[Teleoperator] | None = None,
    policy: PreTrainedPolicy | None = None,
    control_time_s: int | None = None,
    single_task: str | None = None,
    display_data: bool = False,
    record_cfg: dict| None = None,
    play_sound_cfg: dict| None = None
):
    if dataset is not None and dataset.fps != fps:
        raise ValueError(f"The dataset fps should be equal to requested fps ({dataset.fps} != {fps}).")

    teleop_arm = teleop_keyboard = None
    if isinstance(teleop, list):
        teleop_keyboard = next((t for t in teleop if isinstance(t, KeyboardTeleop)), None)
        teleop_arm = next(
            (
                t
                for t in teleop
                if isinstance(t, (so100_leader.SO100Leader, so101_leader.SO101Leader, koch_leader.KochLeader))
            ),
            None,
        )

        if not (teleop_arm and teleop_keyboard and len(teleop) == 2 and robot.name == "lekiwi_client"):
            raise ValueError(
                "For multi-teleop, the list must contain exactly one KeyboardTeleop and one arm teleoperator. Currently only supported for LeKiwi robot."
            )

    # if policy is given it needs cleaning up
    if policy is not None:
        policy.reset()

    timestamp = 0

    sub_episode_time_s = []
    if record_cfg is not None:
        # make local copies we can pop from
        sub_episode_time_s = list(record_cfg["sub_episode_time_s"])
        sub_episode_taskinds = list(record_cfg["sub_episode_taskinds"])
        sub_episode_dur_time = record_cfg["sub_episode_dur_time"]
        sub_episode_total_time = sum(sub_episode_dur_time)
        frame_state_schedule = dict(record_cfg.get("frame_state_schedule", {}))
        frame_state_mapping = record_cfg["frame_state_mapping"]
        episode_remaining_dur_cfg = record_cfg.get("episode_remaining_dur_cfg", None)
        # state recording runtime variables
        cur_sub_episode_ind = -1
        with_state_record = False
        play_state_end_sound = True
        cur_frame_state_name = "success"
        cur_frame_state_code = frame_state_mapping["success"]["ind"]
        # recordings for the current subtask (list of dicts with start_s,end_s,state)
        current_recordings: list[dict] | None = None
        current_recording_idx = 0
        current_recording_end_s = None
        # whether loop record in one episode
        loop_task_record_cfgs = record_cfg.get("loop_task_record_cfgs", None)
        if loop_task_record_cfgs:
            num_loop = loop_task_record_cfgs["num_loop"]
            has_looped = 0
            pre_last_sub_episode_start_time = record_cfg["sub_episode_time_s"][-1]

    start_episode_t = time.perf_counter()
    while timestamp < control_time_s:
        start_loop_t = time.perf_counter()

        if events["exit_early"]:
            events["exit_early"] = False
            break

        observation = robot.get_observation()
        if (
            record_cfg and sub_episode_time_s and timestamp >= sub_episode_time_s[0]
        ):
            text = f"当前第{sub_episode_time_s.pop(0)}秒,请开始第{sub_episode_id}个步骤。"
            play_sound(text, tts_url=play_sound_cfg["tts_url"])
            sub_episode_id += 1

        if (
            record_cfg and 
            loop_task_record_cfgs
        ):
            if (
                len(sub_episode_time_s) == 0 and
                timestamp - pre_last_sub_episode_start_time >= sub_episode_dur_time[-1]
            ):
                num_loop -= 1
                has_looped += 1
                if num_loop > 0:
                    sub_episode_time_s = list(record_cfg["sub_episode_time_s"])
                    sub_episode_taskinds = list(record_cfg["sub_episode_taskinds"])
                    interval_time = sub_episode_total_time * has_looped
                    for i in range(len(sub_episode_time_s)):
                        sub_episode_time_s[i] += interval_time
                    # 临时：停止后续循环的frame state录制
                    with_state_record = True
                    frame_state_schedule = None
                else:
                    cur_sub_episode_ind = -1
                    cur_frame_state_code = frame_state_mapping["invalid"]["ind"]
        if (
            record_cfg and 
            episode_remaining_dur_cfg and 
            len(sub_episode_time_s) == 0 and
            timestamp >= episode_remaining_dur_cfg["episode_remaining_start_time"]
        ):
            cur_sub_episode_ind = episode_remaining_dur_cfg["episode_remaining_state"]
            cur_frame_state_code = frame_state_mapping["invalid"]["ind"]

        if record_cfg and len(sub_episode_time_s) and timestamp >= sub_episode_time_s[0]:
            # pop the boundary only when we trigger entering the sub-episode
            sub_episode_time_s.pop(0)
            cur_sub_episode_ind = sub_episode_taskinds.pop(0)
            if play_sound_cfg:
                text = f"开始第{cur_sub_episode_ind}个步骤"
                try:
                    play_sound(text, tts_url=play_sound_cfg["tts_url"])
                except Exception as e:
                    log_say(f"begin recording {cur_sub_episode_ind} step")

            if frame_state_schedule and cur_sub_episode_ind in frame_state_schedule:
                recordings = list(frame_state_schedule.get(cur_sub_episode_ind, []))
                recordings.sort(key=lambda r: r.get("start_s", 0))
                current_recordings = recordings
                current_recording_idx = 0
                frame_state_schedule.pop(cur_sub_episode_ind)
        
        # handle active or upcoming recordings for current subtask
        if (
            record_cfg and 
            current_recordings is not None and 
            current_recording_idx < len(current_recordings)
        ):
            rec = current_recordings[current_recording_idx]
            rec_start = float(rec["start_s"])
            rec_end = float(rec["end_s"])
            rec_state = rec.get("state")
            if len(sub_episode_time_s):
                next_subtask_start_t = sub_episode_time_s[0]
            else:
                next_subtask_start_t = min(
                    timestamp + sub_episode_dur_time[-1],
                    control_time_s
                )
            if next_subtask_start_t - rec_end < 0.5:
                play_state_end_sound = False
            if not with_state_record and timestamp >= rec_start:
                if play_sound_cfg:
                    state_text = f"{frame_state_mapping[rec_state]['lang']} 录制"
                    try:
                        play_sound(state_text, tts_url=play_sound_cfg["tts_url"])
                    except Exception as e:
                        log_say(f"{rec_state} recording")                
                with_state_record = True
                cur_frame_state_name = rec_state
                cur_frame_state_code = frame_state_mapping[rec_state]["ind"]
                current_recording_end_s = rec_end

            # stop recording when past end time
            if with_state_record and  timestamp >= current_recording_end_s:
                if play_sound_cfg is not None and play_state_end_sound:
                    stop_text = f"{frame_state_mapping[cur_frame_state_name]['lang']} 终止"
                    try:
                        play_sound(stop_text, tts_url=play_sound_cfg["tts_url"])
                    except Exception as e:
                        log_say(f"stop {cur_frame_state_name} recording")                
                with_state_record = False
                cur_frame_state_name = "success"
                cur_frame_state_code = frame_state_mapping["success"]["ind"]
                current_recording_idx += 1
                if current_recording_idx >= len(current_recordings):
                    current_recordings = None
            

        if policy is not None or dataset is not None:
            observation_frame = build_dataset_frame(dataset.features, observation, prefix="observation")

        if policy is not None:
            action_values = predict_action(
                observation_frame,
                policy,
                get_safe_torch_device(policy.config.device),
                policy.config.use_amp,
                task=single_task,
                robot_type=robot.robot_type,
            )
            action = {key: action_values[i].item() for i, key in enumerate(robot.action_features)}
        elif policy is None and isinstance(teleop, Teleoperator):
            action = teleop.get_action()
        elif policy is None and "arx" in robot.name:
            action = robot.get_joint_observations()
        elif policy is None and isinstance(teleop, list):
            # TODO(pepijn, steven): clean the record loop for use of multiple robots (possibly with pipeline)
            arm_action = teleop_arm.get_action()
            arm_action = {f"arm_{k}": v for k, v in arm_action.items()}

            keyboard_action = teleop_keyboard.get_action()
            base_action = robot._from_keyboard_to_base_action(keyboard_action)

            action = {**arm_action, **base_action} if len(base_action) > 0 else arm_action
        else:
            logging.info(
                "No policy or teleoperator provided, skipping action generation."
                "This is likely to happen when resetting the environment without a teleop device."
                "The robot won't be at its rest position at the start of the next episode."
            )
            continue

        # Action can eventually be clipped using `max_relative_target`,
        # so action actually sent is saved in the dataset.
        if "arx" in robot.name:
            sent_action = robot.send_teleop_action(action)
        else:
            # print(f"Sending action: {action}")
            sent_action = robot.send_action(action)

        if dataset is not None:
            action_frame = build_dataset_frame(dataset.features, sent_action, prefix="action")
            frame = {**observation_frame, **action_frame}
            dataset.add_frame(
                frame, 
                task=single_task,
                sub_task=f"{cur_sub_episode_ind - 1}_{cur_frame_state_code}" 
                if record_cfg is not None 
                else None,
            )

        if display_data:
            log_rerun_data(observation, action)

        dt_s = time.perf_counter() - start_loop_t
        busy_wait(1 / fps - dt_s)

        timestamp = time.perf_counter() - start_episode_t


# record入口
@parser.wrap()
def record(cfg: RecordConfig) -> LeRobotDataset:
    init_logging()
    logging.info(pformat(asdict(cfg)))
    if cfg.display_data:
        _init_rerun(session_name="recording")

    # 被操控的机器人piper
    robot = make_robot_from_config(cfg.robot)
    teleop = make_teleoperator_from_config(cfg.teleop) if cfg.teleop is not None else None

    action_features = hw_to_dataset_features(robot.action_features, "action", cfg.dataset.video)
    obs_features = hw_to_dataset_features(robot.observation_features, "observation", cfg.dataset.video)
    dataset_features = {**action_features, **obs_features}

    if cfg.resume:
        dataset = LeRobotDataset(
            cfg.dataset.repo_id,
            root=cfg.dataset.root,
            batch_encoding_size=cfg.dataset.video_encoding_batch_size,
        )

        if hasattr(robot, "cameras") and len(robot.cameras) > 0:
            dataset.start_image_writer(
                num_processes=cfg.dataset.num_image_writer_processes,
                num_threads=cfg.dataset.num_image_writer_threads_per_camera * len(robot.cameras),
            )
        sanity_check_dataset_robot_compatibility(dataset, robot, cfg.dataset.fps, dataset_features)
    else:
        # Create empty dataset or load existing saved episodes
        sanity_check_dataset_name(cfg.dataset.repo_id, cfg.policy)
        dataset = LeRobotDataset.create(
            cfg.dataset.repo_id,
            cfg.dataset.fps,
            root=cfg.dataset.root,
            robot_type=robot.name,
            features=dataset_features,
            use_videos=cfg.dataset.video,
            image_writer_processes=cfg.dataset.num_image_writer_processes,
            image_writer_threads=cfg.dataset.num_image_writer_threads_per_camera * len(robot.cameras),
            batch_encoding_size=cfg.dataset.video_encoding_batch_size,
        )

    # Load pretrained policy
    policy = None if cfg.policy is None else make_policy(cfg.policy, ds_meta=dataset.meta)

    robot.connect()
    if teleop is not None:
        teleop.connect()

    listener, events = init_keyboard_listener()

    # parse record config yaml file
    if cfg.record_yaml_path is not None:
        record_cfg = parse_record_config(
            cfg.record_yaml_path,
            cfg.dataset.episode_time_s,
            cfg.record_task,
        )
    else:
        record_cfg = None
    
    if record_cfg and record_cfg.get("sub_episode_task_json", None) is not None:
        cp_path = dataset.meta.root
        subtask_json = "annotations/subtask_annotations.jsonl"
        if not os.path.exists(os.path.join(cp_path, "annotations")):
            os.makedirs(os.path.join(cp_path, "annotations"))
        shutil.copy(record_cfg["sub_episode_task_json"], os.path.join(cp_path, subtask_json))

    with VideoEncodingManager(dataset):
        recorded_episodes = 0
        while recorded_episodes < cfg.dataset.num_episodes and not events["stop_recording"]:
            try:
                if cfg.play_sounds:
                    play_sound(f"请开始第{recorded_episodes + 1}个事件录制。", cfg.tts_url)
            except Exception as e:
                log_say(f"Recording episode {dataset.num_episodes}", cfg.play_sounds)
            record_loop(
                robot=robot,
                events=events,
                fps=cfg.dataset.fps,
                teleop=teleop,
                policy=policy,
                dataset=dataset,
                control_time_s=cfg.dataset.episode_time_s,
                single_task=cfg.dataset.single_task,
                display_data=cfg.display_data,
                record_cfg=record_cfg,
                play_sound_cfg={
                    "tts_url": cfg.tts_url,
                } if cfg.play_sounds else None,
            )

            # Execute a few seconds without recording to give time to manually reset the environment
            # Skip reset for the last episode to be recorded
            if not events["stop_recording"] and (
                (recorded_episodes < cfg.dataset.num_episodes - 1) or events["rerecord_episode"]
            ):
                try:
                    if cfg.play_sounds:
                        play_sound(f"请重置环境。", cfg.tts_url)
                except Exception as e:
                    log_say("Reset the environment", cfg.play_sounds)
                record_loop(
                    robot=robot,
                    events=events,
                    fps=cfg.dataset.fps,
                    teleop=teleop,
                    control_time_s=cfg.dataset.reset_time_s,
                    single_task=cfg.dataset.single_task,
                    display_data=cfg.display_data,
                )

            if events["rerecord_episode"]:
                try:
                    if cfg.play_sounds:
                        play_sound("请重新录制。", cfg.tts_url)
                except Exception as e:
                    log_say("Re-record episode", cfg.play_sounds)   
                events["rerecord_episode"] = False
                events["exit_early"] = False
                dataset.clear_episode_buffer()
                continue

            dataset.save_episode()
            recorded_episodes += 1
    try:
        if cfg.play_sounds:
            play_sound("录制完成, 谢谢。", tts_url=cfg.tts_url)
    except Exception as e:
        log_say("Stop recording", cfg.play_sounds, blocking=True)

    robot.disconnect()
    if teleop is not None:
        teleop.disconnect()

    if not is_headless() and listener is not None:
        listener.stop()

    if cfg.dataset.push_to_hub:
        dataset.push_to_hub(tags=cfg.dataset.tags, private=cfg.dataset.private)
    try:
        if cfg.play_sounds:
            play_sound("程序退出，谢谢。",  tts_url=cfg.tts_url)
    except Exception as e:
        log_say("Exiting", cfg.play_sounds)
    return dataset


def main():
    record()


if __name__ == "__main__":
    main()
