# Copyright 2024 The HuggingFace Inc. team. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Records a dataset. Actions for the robot can be either generated by teleoperation or by a policy.

Example:

```shell
lerobot-record \
    --robot.type=so100_follower \
    --robot.port=/dev/tty.usbmodem58760431541 \
    --robot.cameras="{laptop: {type: opencv, camera_index: 0, width: 640, height: 480}}" \
    --robot.id=black \
    --dataset.repo_id=aliberts/record-test \
    --dataset.num_episodes=2 \
    --dataset.single_task="Grab the cube" \
    # <- Teleop optional if you want to teleoperate to record or in between episodes with a policy \
    # --teleop.type=so100_leader \
    # --teleop.port=/dev/tty.usbmodem58760431551 \
    # --teleop.id=blue \
    # <- Policy optional if you want to record with a policy \
    # --policy.path=${HF_USER}/my_policy \
```

Example recording with bimanual so100:
```shell
lerobot-record \
  --robot.type=bi_so100_follower \
  --robot.left_arm_port=/dev/tty.usbmodem5A460851411 \
  --robot.right_arm_port=/dev/tty.usbmodem5A460812391 \
  --robot.id=bimanual_follower \
  --robot.cameras='{
    left: {"type": "opencv", "index_or_path": 0, "width": 640, "height": 480, "fps": 30},
    top: {"type": "opencv", "index_or_path": 1, "width": 640, "height": 480, "fps": 30},
    right: {"type": "opencv", "index_or_path": 2, "width": 640, "height": 480, "fps": 30}
  }' \
  --teleop.type=bi_so100_leader \
  --teleop.left_arm_port=/dev/tty.usbmodem5A460828611 \
  --teleop.right_arm_port=/dev/tty.usbmodem5A460826981 \
  --teleop.id=bimanual_leader \
  --display_data=true \
  --dataset.repo_id=${HF_USER}/bimanual-so100-handover-cube \
  --dataset.num_episodes=25 \
  --dataset.single_task="Grab and handover the red cube to the other arm"
```
"""

import logging
import os
import time
import threading
from dataclasses import asdict, dataclass
from pathlib import Path
from pprint import pformat

from lerobot.cameras import (  # noqa: F401
    CameraConfig,  # noqa: F401
)
from lerobot.cameras.opencv.configuration_opencv import OpenCVCameraConfig  # noqa: F401
from lerobot.cameras.realsense.configuration_realsense import RealSenseCameraConfig  # noqa: F401
from lerobot.configs import parser
from lerobot.configs.policies import PreTrainedConfig
from lerobot.datasets.image_writer import safe_stop_image_writer
from lerobot.datasets.lerobot_dataset import LeRobotDataset
from lerobot.datasets.utils import build_dataset_frame, hw_to_dataset_features
from lerobot.datasets.video_utils import VideoEncodingManager
from lerobot.policies.factory import make_policy
from lerobot.policies.pretrained import PreTrainedPolicy
from lerobot.robots import (  # noqa: F401
    Robot,
    RobotConfig,
    bi_so100_follower,
    #arx_x5_python,
    hope_jr,
    koch_follower,
    make_robot_from_config,
    so100_follower,
    so101_follower,
    piper,
)
from lerobot.teleoperators import (  # noqa: F401
    Teleoperator,
    TeleoperatorConfig,
    bi_so100_leader,
    homunculus,
    koch_leader,
    make_teleoperator_from_config,
    so100_leader,
    so101_leader,
)
from lerobot.teleoperators.keyboard.teleop_keyboard import KeyboardTeleop
from lerobot.utils.control_utils import (
    init_keyboard_listener,
    is_headless,
    #predict_action,
    sanity_check_dataset_name,
    sanity_check_dataset_robot_compatibility,
)
from lerobot.utils.robot_utils import busy_wait
from lerobot.utils.utils import (
    get_safe_torch_device,
    init_logging,
)
from lerobot.utils.visualization_utils import _init_rerun, log_rerun_data

# pi0
from openpi_client import websocket_client_policy as _websocket_client_policy
import einops
from openpi_client import image_tools
from openpi_client.runtime import environment as _environment
import numpy as np
import requests
import io
import pygame

# 设置音频驱动
os.environ["SDL_AUDIODRIVER"] = "pulse"


def play_sound_seq(
    text: str = "你好啊，我是三零九零。", reference_id: str = "taozi", tts_url: str = "http://127.0.0.1:8080/v1/tts"
):
    """播放TTS音频序列"""
    payload = {"text": text, "format": "wav", "reference_id": reference_id}
    wav_bytes = requests.post(tts_url, json=payload).content

    pygame.mixer.init()
    sound = pygame.mixer.Sound(io.BytesIO(wav_bytes))

    sound.set_volume(4200.0)  # 调整音量，1.0 为原始，2.0 放大一倍
    sound.play()

    time.sleep(sound.get_length() + 0.5)  # 多给 0.5s 缓冲
    pygame.mixer.quit()


def play_sound(
    text: str = "你好啊，我是三零九零。", reference_id: str = "taozi", tts_url: str = "http://127.0.0.1:8080/v1/tts"
):
    """在单独线程中播放TTS音频"""
    thread = threading.Thread(target=play_sound_seq, args=(text, reference_id, tts_url))
    thread.start()



class Gr00tRobotInferenceClient:
    """The exact keys used is defined in modality.json

    This currently only supports so100_follower, so101_follower
    modify this code to support other robots with other keys based on modality.json
    """

    def __init__(
        self,
        host="localhost",
        port=8000,
        camera_keys=[],
        robot_state_keys=[],
        show_images=True,
    ):
        self.policy = _websocket_client_policy.WebsocketClientPolicy(
                host=host,
                port=port,
            )
        self.camera_keys = camera_keys
        self.robot_state_keys = robot_state_keys
        self.show_images = show_images
        # assert (
        #     len(robot_state_keys) == 6
        # ), f"robot_state_keys should be size 6, but got {len(robot_state_keys)} "
        # self.modality_keys = ["left_arm", "left_gripper", "right_arm", "right_gripper"]
        # self.modality_keys = ["actions"]

    def get_action(self, observation_dict, lang: str):
        # first add the images
        # ['joint_0.pos', 'joint_1.pos', 'joint_2.pos', 'joint_3.pos', 'joint_4.pos', 'joint_5.pos', 'joint_6.pos', 
        # 'head', 'right_wrist']
        # print("----get_actionobservation_dict keys:", list(observation_dict.keys()))
        # ['observation.state', 'observation.images.head', 'observation.images.right_wrist', 'task', 'robot_type']
        obs_dict = {key: observation_dict["observation.images."+key] for key in self.camera_keys}

        # show images
        # if self.show_images:
        #     view_img(obs_dict)

        for k in list(obs_dict.keys()):
            if "_depth" in k:
                del obs_dict[k]

        for cam_name in obs_dict:
            img = obs_dict[cam_name].squeeze(0)
            # print(f"---get_action cam_name: {cam_name}, shape: {img.shape}")
            obs_dict[cam_name] = einops.rearrange(img, "h w c -> c h w")
            # print(f"---get_action cam_name: {cam_name}, shape: {img.shape}")

        # state = np.array([observation_dict[k] for k in self.robot_state_keys]).astype(np.float32)
        state = observation_dict['observation.state']
        # print(f"---state shape: {state.shape}, dtype: {state.dtype}, min: {state.min()}, max: {state.max()}, mean: {state.mean()}")

        observation = {
            "observation/front_image": obs_dict["head"],
            "observation/wrist_image": obs_dict["right_wrist"],
            # "observation/wrist_image_lf": obs_dict["left_wrist"],
            "observation/state": state,
            "prompt": lang,
        }

        observation_native = observation
        for k, v in observation_native.items():
            # print(f"observation_native key: {k}, type: {type(v)}")
            observation_native[k] = v.cpu().detach().numpy() if hasattr(v, "cpu") else v
            if "image" in k:
                observation_native[k] = observation_native[k].transpose(2, 0, 1)  # HWC to CHW
            if "state" in k:
                # print(f"---get_action state shape: {observation_native[k].shape} type: {type(observation_native[k])}")
                observation_native[k] = observation_native[k].squeeze(axis=0)  # remove extra dims
            # print(f"observation_native key: {k}, shape: {observation_native[k].shape if hasattr(observation_native[k], 'shape') else 'no shape'}, dtype: {type(observation_native[k])}")


        action = self.policy.infer(observation_native)
        '''
        print(f"---observation keys and shape---:")
        [print(k, value.shape, value.dtype, value.min(), value.max(), value.mean()) for k, value in observation.items() if isinstance(value, np.ndarray)]
        import pdb; pdb.set_trace() # exit()
        test_image = observation['observation/front_image'].transpose([1,2,0])[:,:,::-1]
        import cv2; cv2.imwrite("front_test.png", test_image)
        print("action keys(): ", action.keys())
        print("action/action.shape: ", action["actions"].shape)
        # print min/max and mean of each action dimension
        for i in range(action["actions"].shape[1]):
            print(f"action dimension {i}: min {np.min(action['actions'][:,i])}, max {np.max(action['actions'][:,i])}, mean {np.mean(action['actions'][:,i])}")

        '''

        # convert the action chunk to a list of dict[str, float]
        lerobot_actions = []
        action_horizon = action["actions"].shape[0]
        for idx in range(action_horizon):
            action_dict = self._convert_to_lerobot_action(action["actions"], idx)
            lerobot_actions.append(action_dict)
        return lerobot_actions

    def _convert_to_lerobot_action(
        self, action_chunk: dict[str, np.array], idx: int
    ) -> dict[str, float]:
        """
        This is a magic function that converts the action chunk to a dict[str, float]
        This is because the action chunk is a dict[str, np.array]
        and we want to convert it to a dict[str, float]
        so that we can send it to the robot
        """
        assert action_chunk.shape[-1] == len(self.robot_state_keys), "this should be size 6"
        # convert the action to dict[str, float]
        action_dict = {key: action_chunk[idx, i] for i, key in enumerate(self.robot_state_keys)}
        return action_dict



@dataclass
class DatasetRecordConfig:
    # Dataset identifier. By convention it should match '{hf_username}/{dataset_name}' (e.g. `lerobot/test`).
    repo_id: str
    # A short but accurate description of the task performed during the recording (e.g. "Pick the Lego block and drop it in the box on the right.")
    single_task: str
    # Root directory where the dataset will be stored (e.g. 'dataset/path').
    root: str | Path | None = None
    # Limit the frames per second.
    fps: int = 30
    # Number of seconds for data recording for each episode.
    episode_time_s: int | float = 60
    # Number of seconds for resetting the environment after each episode.
    reset_time_s: int | float = 60
    # Number of episodes to record.
    num_episodes: int = 50
    # Encode frames in the dataset into video
    video: bool = True
    # Upload dataset to Hugging Face hub.
    push_to_hub: bool = True
    # Upload on private repository on the Hugging Face hub.
    private: bool = False
    # Add tags to your dataset on the hub.
    tags: list[str] | None = None
    # Number of subprocesses handling the saving of frames as PNG. Set to 0 to use threads only;
    # set to ≥1 to use subprocesses, each using threads to write images. The best number of processes
    # and threads depends on your system. We recommend 4 threads per camera with 0 processes.
    # If fps is unstable, adjust the thread count. If still unstable, try using 1 or more subprocesses.
    num_image_writer_processes: int = 0
    # Number of threads writing the frames as png images on disk, per camera.
    # Too many threads might cause unstable teleoperation fps due to main thread being blocked.
    # Not enough threads might cause low camera fps.
    num_image_writer_threads_per_camera: int = 4
    # Number of episodes to record before batch encoding videos
    # Set to 1 for immediate encoding (default behavior), or higher for batched encoding
    video_encoding_batch_size: int = 1
    

    def __post_init__(self):
        if self.single_task is None:
            raise ValueError("You need to provide a task as argument in `single_task`.")

import torch
from copy import copy

def predict_action(
    observation: dict[str, np.ndarray],
    policy: Gr00tRobotInferenceClient,
    device: torch.device,
    use_amp: bool,
    task: str | None = None,
    robot_type: str | None = None,
):
    observation = copy(observation)
    with (
        torch.inference_mode(),
        # torch.autocast(device_type=device.type) if device.type == "cuda" and use_amp else nullcontext(),
        torch.autocast(device_type="cuda"),
    ):
        # Convert to pytorch format: channel first and float32 in [0,1] with batch dimension
        for name in observation:
            observation[name] = torch.from_numpy(observation[name])
            # print(f"---predict_action observation key: {name}, shape: {observation[name].shape}, dtype: {observation[name].dtype}")
            # observation_native key: observation/front_image, type: <class 'torch.Tensor'>
            # observation_native key: observation/wrist_image, type: <class 'torch.Tensor'>
            # observation_native key: observation/state, type: <class 'torch.Tensor'>
            if "image" in name:
                observation[name] = observation[name].type(torch.float32) / 255
                observation[name] = observation[name].permute(2, 0, 1).contiguous()
            observation[name] = observation[name].unsqueeze(0)
            observation[name] = observation[name].to(device)

        observation["task"] = task if task else ""
        observation["robot_type"] = robot_type if robot_type else ""

        # Compute the next action with the policy
        # based on the current observation
        # action = policy.select_action(observation)

        action = policy.get_action(observation, task)
        # print(f"===predict_action action[0]: {action[0]}, dtype: {type(action[0])}, len: {len(action)}")

        # Remove batch dimension
        # action = action.squeeze(0)

        # # Move to cpu, if not already the case
        # action = action.to("cpu")

    return action

@dataclass
class RecordConfig:
    robot: RobotConfig
    dataset: DatasetRecordConfig
    # Whether to control the robot with a teleoperator
    teleop: TeleoperatorConfig | None = None
    # Whether to control the robot with a policy
    policy: PreTrainedConfig | None = None
    # Display all cameras on screen
    display_data: bool = False
    # Use vocal synthesis to read events.
    play_sounds: bool = True
    # Resume recording on an existing dataset.
    resume: bool = False

    # TTS服务地址
    tts_url: str = "http://127.0.0.1:8080/v1/tts"

    policy_host: str = "localhost"
    policy_port: int = 8000

    def __post_init__(self):
        # HACK: We parse again the cli args here to get the pretrained path if there was one.
        policy_path = parser.get_path_arg("policy")
        if policy_path:
            cli_overrides = parser.get_cli_overrides("policy")
            self.policy = PreTrainedConfig.from_pretrained(policy_path, cli_overrides=cli_overrides)
            self.policy.pretrained_path = policy_path

        # if self.teleop is None and self.policy is None:
        #     if "arx" not in self.robot.type:
        #         raise ValueError("For robots with a mobile base, you need to provide a teleoperator or a policy to control the base.")
        #     else:
        #         logging.warning("No teleoperator or policy provided, the robot will stay still during recording.")
    @classmethod
    def __get_path_fields__(cls) -> list[str]:
        """This enables the parser to load config from the policy using `--policy.path=local/dir`"""
        return ["policy"]


@safe_stop_image_writer
def record_loop(
    robot: Robot,
    events: dict,
    fps: int,
    dataset: LeRobotDataset | None = None,
    teleop: Teleoperator | list[Teleoperator] | None = None,
    policy: PreTrainedPolicy | None = None,
    control_time_s: int | None = None,
    single_task: str | None = None,
    display_data: bool = False,
    chunk_exe: int = 40,
):
    if dataset is not None and dataset.fps != fps:
        raise ValueError(f"The dataset fps should be equal to requested fps ({dataset.fps} != {fps}).")

    teleop_arm = teleop_keyboard = None
    if isinstance(teleop, list):
        teleop_keyboard = next((t for t in teleop if isinstance(t, KeyboardTeleop)), None)
        teleop_arm = next(
            (
                t
                for t in teleop
                if isinstance(t, (so100_leader.SO100Leader, so101_leader.SO101Leader, koch_leader.KochLeader))
            ),
            None,
        )

        if not (teleop_arm and teleop_keyboard and len(teleop) == 2 and robot.name == "lekiwi_client"):
            raise ValueError(
                "For multi-teleop, the list must contain exactly one KeyboardTeleop and one arm teleoperator. Currently only supported for LeKiwi robot."
            )

    # if policy is given it needs cleaning up
    # if policy is not None:
    #     policy.reset()

    timestamp = 0
    start_episode_t = time.perf_counter()
    action_values = None
    count_frames = 0
    action = None
    while timestamp < control_time_s:
        start_loop_t = time.perf_counter()

        if events["exit_early"]:
            events["exit_early"] = False
            break
        
        #---record loop-observation keys: 
        # ['joint_0.pos', 'joint_1.pos', 'joint_2.pos', 'joint_3.pos', 'joint_4.pos', 'joint_5.pos', 'joint_6.pos', 
        # 'head', 'right_wrist']
        observation = robot.get_observation()
        # print(f"---record loop-observation keys:", list(observation.keys()))

        if policy is not None or dataset is not None:
            observation_frame = build_dataset_frame(dataset.features, observation, prefix="observation")

        if policy is not None:
            print(f"===record_loop timestamp: {count_frames}, chunk_exe: {chunk_exe} , timestamp % chunk_exe: {count_frames % chunk_exe == 0}")
            if count_frames % chunk_exe == 0:
                action_values = predict_action(
                    observation_frame,
                    policy,
                    # get_safe_torch_device(policy.config.device),
                    device="cuda",
                    use_amp=True,
                    task=single_task,
                    robot_type=robot.robot_type,
                )
                count_frames = 0
            cur_action_idx = int(count_frames % chunk_exe)
            cur_action = action_values[cur_action_idx]
            print(f"===record_loop cur_action_idx: {cur_action_idx}, cur_action: {cur_action}, dtype: {type(cur_action)}, len: {len(cur_action)}")
            print("===record_loop robot.action_features:", robot.action_features)
            action = {key: cur_action[key] for i, key in enumerate(robot.action_features)}
            print(f"===== action: {action}")
        elif policy is None and isinstance(teleop, Teleoperator):
            action = teleop.get_action()
        elif policy is None and "arx" in robot.name:
            action = robot.get_joint_observations()
        elif policy is None and isinstance(teleop, list):
            # TODO(pepijn, steven): clean the record loop for use of multiple robots (possibly with pipeline)
            arm_action = teleop_arm.get_action()
            arm_action = {f"arm_{k}": v for k, v in arm_action.items()}

            keyboard_action = teleop_keyboard.get_action()
            base_action = robot._from_keyboard_to_base_action(keyboard_action)

            action = {**arm_action, **base_action} if len(base_action) > 0 else arm_action
        # else:
        #     logging.info(
        #         "No policy or teleoperator provided, skipping action generation."
        #         "This is likely to happen when resetting the environment without a teleop device."
        #         "The robot won't be at its rest position at the start of the next episode."
        #     )
        #     continue

        # Action can eventually be clipped using `max_relative_target`,
        # so action actually sent is saved in the dataset.
        if "arx" in robot.name:
            sent_action = robot.send_teleop_action(action)
        else:
            # print(f"Sending action: {action}")
            # {'shoulder_pan.pos': 2.45901639344261, 'shoulder_lift.pos': -96.75352413498504, 'elbow_flex.pos': 99.90900818926295, 
            #'wrist_flex.pos': 26.254666113645797, 'wrist_roll.pos': 3.8339438339438487, 'gripper.pos': 0.20533880903490762}
            print(f"Sending action: {action}")
            sent_action = robot.send_action(action)

        if dataset is not None:
            action_frame = build_dataset_frame(dataset.features, sent_action, prefix="action")
            frame = {**observation_frame, **action_frame}
            dataset.add_frame(frame, task=single_task)

        if display_data:
            log_rerun_data(observation, action)

        dt_s = time.perf_counter() - start_loop_t
        busy_wait(1 / fps - dt_s)

        timestamp = time.perf_counter() - start_episode_t
        count_frames += 1


# record入口
@parser.wrap()
def record(cfg: RecordConfig) -> LeRobotDataset:

    init_logging()
    logging.info(pformat(asdict(cfg)))
    if cfg.display_data:
        _init_rerun(session_name="recording")

    # 被操控的机器人piper
    robot = make_robot_from_config(cfg.robot)
    # 遥操机器人-> policy
    teleop = make_teleoperator_from_config(cfg.teleop) if cfg.teleop is not None else None
    

    action_features = hw_to_dataset_features(robot.action_features, "action", cfg.dataset.video)
    obs_features = hw_to_dataset_features(robot.observation_features, "observation", cfg.dataset.video)
    dataset_features = {**action_features, **obs_features}

    if cfg.resume:
        dataset = LeRobotDataset(
            cfg.dataset.repo_id,
            root=cfg.dataset.root,
            batch_encoding_size=cfg.dataset.video_encoding_batch_size,
        )

        if hasattr(robot, "cameras") and len(robot.cameras) > 0:
            dataset.start_image_writer(
                num_processes=cfg.dataset.num_image_writer_processes,
                num_threads=cfg.dataset.num_image_writer_threads_per_camera * len(robot.cameras),
            )
        sanity_check_dataset_robot_compatibility(dataset, robot, cfg.dataset.fps, dataset_features)
    else:
        # Create empty dataset or load existing saved episodes
        sanity_check_dataset_name(cfg.dataset.repo_id, cfg.policy)
        dataset = LeRobotDataset.create(
            cfg.dataset.repo_id,
            cfg.dataset.fps,
            root=cfg.dataset.root,
            robot_type=robot.name,
            features=dataset_features,
            use_videos=cfg.dataset.video,
            image_writer_processes=cfg.dataset.num_image_writer_processes,
            image_writer_threads=cfg.dataset.num_image_writer_threads_per_camera * len(robot.cameras),
            batch_encoding_size=cfg.dataset.video_encoding_batch_size,
        )

    robot.connect()
    # Load pretrained policy
    # policy = None if cfg.policy is None else make_policy(cfg.policy, ds_meta=dataset.meta)

    #connect to pretrained policy server
    camera_keys = list(cfg.robot.cameras.keys())
    init_obs = robot.get_observation()
    # print("Initial observation keys:", list(init_obs.keys()))
    # Initial observation keys: ['joint_0.pos', 'joint_1.pos', 'joint_2.pos', 'joint_3.pos', 'joint_4.pos', 
    # 'joint_5.pos', 'joint_6.pos', 'head', 'right_wrist']
    joint_keys = [k for k in init_obs.keys() if k not in camera_keys and '.pos' in k]
    policy = Gr00tRobotInferenceClient(
        host=cfg.policy_host,
        port=cfg.policy_port,
        camera_keys=camera_keys,
        robot_state_keys=joint_keys,
    )

    
    if teleop is not None:
        teleop.connect()

    listener, events = init_keyboard_listener()

    with VideoEncodingManager(dataset):
        recorded_episodes = 0
        while recorded_episodes < cfg.dataset.num_episodes and not events["stop_recording"]:
            logging.info(f"Recording episode {recorded_episodes + 1}/{cfg.dataset.num_episodes}")
            if cfg.play_sounds:
                play_sound(f"请开始第{recorded_episodes + 1}个事件录制。", tts_url=cfg.tts_url)
            record_loop(
                robot=robot,
                events=events,
                fps=cfg.dataset.fps,
                teleop=teleop,
                policy=policy,
                dataset=dataset,
                control_time_s=cfg.dataset.episode_time_s,
                single_task=cfg.dataset.single_task,
                display_data=cfg.display_data,
            )

            # Execute a few seconds without recording to give time to manually reset the environment
            # Skip reset for the last episode to be recorded
            if not events["stop_recording"] and (
                (recorded_episodes < cfg.dataset.num_episodes - 1) or events["rerecord_episode"]
            ):
                if cfg.play_sounds:
                    play_sound("请重置环境。", tts_url=cfg.tts_url)
                # record_loop(
                #     robot=robot,
                #     events=events,
                #     fps=cfg.dataset.fps,
                #     teleop=teleop,
                #     control_time_s=cfg.dataset.reset_time_s,
                #     single_task=cfg.dataset.single_task,
                #     display_data=cfg.display_data,
                # )

            if events["rerecord_episode"]:
                if cfg.play_sounds:
                    play_sound("请重新录制。", tts_url=cfg.tts_url)
                events["rerecord_episode"] = False
                events["exit_early"] = False
                dataset.clear_episode_buffer()
                continue

            dataset.save_episode()
            recorded_episodes += 1

    if cfg.play_sounds:
        play_sound("录制完成, 谢谢。", reference_id="taozi", tts_url=cfg.tts_url)

    robot.disconnect()
    if teleop is not None:
        teleop.disconnect()

    if not is_headless() and listener is not None:
        listener.stop()

    if cfg.dataset.push_to_hub:
        dataset.push_to_hub(tags=cfg.dataset.tags, private=cfg.dataset.private)

    if cfg.play_sounds:
        play_sound("程序退出，谢谢。", reference_id="taozi", tts_url=cfg.tts_url)
    return dataset


def main():
    record()


if __name__ == "__main__":
    main()
